title: 'Hallee Adelman'
default_lang: en
author:
  name: 'Hallee Adelman'
  email: hallee@adelmans.net
taxonomies:
  - year
  - author
  - category
  - tag
metadata:
  description: 'Website of Hallee Adelman, Author and Founder of World of Ha'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
